# ===================================================================
# VnPy CTA 策略儀表板 (v5.0 - 智慧空間調整版)
# ===================================================================
mode: "optimize"  # 指定執行優化任務
# ===================================================================
# 1. 交易環境 (Session)
# ===================================================================
session:
  vt_symbol: "TXFR1.TAIFEX"
  interval: "1m"
  start_date: "2017-10-01"
  end_date: "2025-05-01"

# ===================================================================
# 2. 回測引擎 (Engine)
# ===================================================================
engine:
  capital: 1_000_000
  rate: 0.00001425
  slippage: 0.1
  size: 1
  pricetick: 0.2

# ===================================================================
# 3. 策略配置 (Strategy)
# ===================================================================
strategy:
  name: "DmiTrendStrategy"

# ===================================================================
# 4. 參數優化 (Optimization)
# ===================================================================
optimization:
  target: "sharpe_ratio"
  algorithm: "GA"
  processes: 8      # 您可以根據您的硬體調整核心數

  # --- 核心修改：切換到手動模式 ---
  auto_detect_params: false  # <--- 1. 將此設為 false，關閉自動探索

  ga_settings:
    population_size: 100
    ngen_size: 20

  # --- 手動精調參數空間 ---
  # 2. 在此處定義您想要的精確優化範圍
  param_space:
    dmi_period: [2, 60, 2]         # dmi 週期從 2 到 60，每隔 2 取一個值
    adx_threshold: [-10, 75, 5]  
#
# ===================================================================
# 5. & 6. (walk_forward, reporting 區塊保持不變)
# ===================================================================
walk_forward:
  in_sample_days: 250
  out_of_sample_days: 90

reporting:
  output_folder: "results"
  top_n_results: 15
  save_trades_log: true
  generate_quantstats_report: true