# ??????????????????
# -------------------------------------------------------------
# ????????????????????????????????????????
[postgresql]
dsn_env = "PG_DSN"                # ??.env ??????????
schema = "public"
batch_size = 1000                 # ????????????
max_workers = 4                   # ?????????
copy_enabled = true               # ?????? COPY?????fallback executemany
copy_timeout_ms = 3000

[ingest]
channels = ["trades", "orderbook", "quotes"]
l2_depth = 5
heartbeat_sec = 15
raw_backpressure_ms = 750         # ????????????????? raw ??????
latency_warn_ms = 350

[retry]
max_attempts = 5
backoff_initial_ms = 500
backoff_multiplier = 2.0
backoff_cap_ms = 15000

[replay]
chunk_seconds = 60                # tools/replay_ws_raw.py ??????????????max_parallel = 2

[monitor]
ntp_server = "pool.ntp.org"
drift_tolerance_ms = 100

[logging]
level = "INFO"
json = false
log_path = "logs/fubon_ingest.log"

